### ISSUE TITLE
Change Heroku button to use offiical Heroku Redis instead of RedisToGo

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/appointment-reminders-flask#3]
Starting up the app via Heroku worked perfectly for me.

If possible, I think it would be better if we used the recently released official Heroku Redis addon instead of RedisToGo:

https://addons.heroku.com/heroku-redis?utm_campaign=search&utm_medium=dashboard&utm_source=addons

When I was building the appointment-reminders-django tutorial, my Heroku button deploys would sometimes crash because RedisToGo was tripping up the deploy. Developers trying to use our app might have better luck with the official Redis addon.

**Comment by jsantos17** [comment]
Fixed by 02d6c52794355b1a039db0b43adb38d0aa972d67
