### ISSUE TITLE
Provide a response for the / URL

### ISSUE THREAD

**Issue by atbaker** [TwilioDevEd/appointment-reminders-flask#4]
Could you add a redirect so that when users go to [http://localhost:5000](http://localhost:5000) they get redirected to [http://localhost:5000/appointment](http://localhost:5000/appointment)? Or, just make the view that serves /appointment serve the root URL instead?

Right now a user will get a 404 error if they go to the root directory of their dev server, which could be confusing for them.

**Comment by jsantos17** [comment]
Fixed by  02d6c52
